// JavaScript Document
var multiLanguage_help_array =new Array();
multiLanguage_help_array = [
							[
							 "USB Extension",
							 "Back",
							 "Use Download Master",
							 "Install the Windows® utility",
							 "step",
							 "Click the Download Master name or icon in the USB application page.",
							 "The Download Master will open in a new browser window. Click \"Add\" to add a download task.",
							 "To download the BitTorrent or NZB file, click \"Choose file\" to upload the *.torrent or *.nzb file.",
							 "To download the FTP, HTTP or Magnet link, copy and paste the URL to the URL field.",
							 "If the FTP site needs username, password, there is an exclamation mark <img src=\"images/appinstall/warning_16X16.png\"> in the task area.",
							 "Please click the exclamation mark to key in the username and password.",
							 "Download and install the Windows® utility.",
							 "Download Now!",
							 "After installing the Windows® utility, double-click the torrent file and it will be added to the Download Master task automatically."
							 ],
							[
							"USB 擴充",
							 "返回",
							 "使用 Download Master",
							 "安裝 Windows® 公用程式",
							 "步驟",
							 "在 USB 應用頁面中點選 Download Master 名稱或圖示。",
							 "Download Master 將在新的瀏覽器中開啟。點選 \"新增\" 加入新的下載任務。",
							 "要下載 BitTorrent 或 NZB 檔案，點選 \"選擇檔案\" 來上傳 *.torrent 或 *.nzb 檔案。",
							 "要下載 FTP、HTTP 或 Magnet 內容，將 URL 複製並粘貼至 URL 區域。",
							 "FTP 站點需要使用者名稱、密碼。在任務區域顯示一個驚歎號<img src=\"images/appinstall/warning_16X16.png\">",
							 "請點選驚歎號來輸入使用者名稱與密碼。",
							 "下載並安裝 Windows® 公用程式。",
							 "現在下載！",
							 "安裝 Windows® 公用程式後，雙擊 torrent 檔案，它將自動被加入 Download Master 任務中。"
							 ],
							[
							 "USB 扩展",
							 "返回",
							 "使用 Download Master",
							 "安装 Windows® 应用程序",
							 "步骤",
							 "在 USB 应用页面中点击 Download Master 名称或图标。",
							 "Download Master 将在新的浏览器中打开。点击【添加】加入新的下载任务。",
							 "要下载 BitTorrent 或 NZB 文件，点击【选择文件】来上传 *.torrent 或 *.nzb 文件。",
							 "要下载 FTP、HTTP 或 Magnet 内容，将 URL 复制并粘贴至 URL 区域。",
							 "FTP 站点需要用户名、密码。在任务区域显示一个叹号<img src=\"images/appinstall/warning_16X16.png\">",
							 "请点击叹号来输入用户名与密码。",
							 "下载并安装 Windows® 应用程序。",
							 "现在下载！",
							 "安装 Windows® 应用程序后，双击 torrent 文件，它将自动被加入 Download Master 任务中。"
							 ],
							[
							 "USB расширение",
							 "назад",
							 "Использование Download Master",
							 "Установите утилиту Windows",
							 "шаг",
							 "На странице USB приложения нажмите ссылку Download Master",
							 "Download Master откроется в новом окне браузера. Нажмите Добавить для добавления загрузки",
							 "Для скачивания BitTorrent или NZB файла, нажмите Выбрать файл для выбора *. торрент или *. NZB файла.",
							 "Для загрузки с FTP, HTTP или Magnet скопируйте и вставьте ссылку в поле URL.",
							 "Если для FTP-сервера требуется имя пользователя и пароль, в области задач появится восклицательный знак <img src=\"images/appinstall/warning_16X16.png\">.",
							 "Нажмите восклицательный знак для ввода имени пользователя и пароля.",
							 "Скачать и установить утилиту для Windows.",
							 "Скачать сейчас!",
							 "После установки утилиты для Windows, дважды щелкните по torrent-файлу и он будет автоматически добавлен в список закачек."
							 ],
							[
							 "Extensions USB",
							 "Précédent",
							 "Utiliser Download Master",
							 "Installer l'utilitaire Windows®",
							 "sÉtape",
							 "Cliquez sur l'icône Download Master à partir de la page des applications USB.",
							 "Download Master s'ouvrira dans une nouvelle fenêtre de votre navigateur Internet. Cliquez sur Ajouter pour créer une nouvelle tâche de téléchargement.",
							 "Pour télécharger le fichier BitTorrent ou NZB, sélectionnez un fichier avec une extension .torrent ou .nzb.",
							 "Pour les téléchargements FTP, HTTP ou Magnet, copiez/collez l'adresse Web dans le champ destiné à l'URL.",
							 "Si le serveur FTP nécessite une authentification (nom d'utilisateur et mot de passe), un point d'exclamation <img src=\"images/appinstall/warning_16X16.png\"> apparaît dans la barre des tâches.",
							 "Cliquez sur le point d'exclamation pour entrer le nom d'utilisateur et le mot de passe.",
							 "Téléchargement et installation de l'utilitaire Windows®.",
							 "Télécharger maintenant !",
							 "Après avoir installé l'utilitaire Windows®, double-cliquez sur le fichier torrent pour qu'il soit automatiquement ajouté à la liste des téléchargements de Download Master."
							 ],
							[
							 "USB-Erweiterung",
							 "Zurück",
							 "Download-Master verwenden",
							 "Windows®-Hilfsprogramm installieren",
							 "Schritt",
							 "Klicken Sie in der USB-Anwendungsseite auf den Namen oder das Symbol von Download Master.",
							 "Download-Master wird in einen neuen Browser-Fenster geöffnet. Klicken Sie auf Hinzufügen, um eine Download-Aufgabe hinzuzufügen",
							 "Um die BitTorrent- oder NZB-Datei herunterzuladen, klicken Sie auf Datei auswählen, um die *.torrent- oder *.nzb-Datei herunterzuladen.",
							 "Um von FTP-, HTTP- oder Magnetlink herunter zu laden, kopieren Sie die URL und fügen Sie diese im URL-Feld ein.",
							 "Falls die FTP-Seite einen Benutzernamen und ein Kennwort erfordert, befindet sich dafür ein Ausrufezeichen <img src=\"images/appinstall/warning_16X16.png\"> im Taskbereich.",
							 "Klicken Sie bitte auf das Ausrufezeichen, um den Benutzernamen und das Kennwort einzugeben.",
							 "Windows®-Hilfsprogramm herunterladen und installieren.",
							 "Jetzt herunterladen!",
							 "Nach der Installation des Hilfsprogramms doppelklicken Sie bitte auf die Torrent-Datei, um Sie automatisch zur Dowload-Aufgabenliste hinzuzufügen."
							 ],
							[
							 "Extensão USB",
							 "voltar",
							 "Usar Download Master",
							 "Instalar o utilitário do Windows®",
							 "passo",
							 "Clique no nome Download Master ou ícone na página do aplicativo USB.",
							 "O Download Master será aberto em uma nova janela do navegador. Clique em Add (Adicionar) para adicionar uma tarefa de download.",
							 "Para baixar o arquivo BitTorrent ou NZB, clique em Choose flie (Escolher arquivo) para fazer o upload do torrent ou arquivo *.nzb.",
							 "Para fazer download do link FTP, HTTP ou Magnet, copie e cole a URL no campo URL.",
							 "Se o site FTP precisar de nome de usuário, senha, há um ponto de exclamação <img src=\"images/appinstall/warning_16X16.png\">na área de tarefas.",
							 "Por favor, clique no ponto de exclamação para introduzir o nome de usuário e senha.",
							 "Baixe e instale o utilitário Windows®.",
							 "Baixar agora!",
							 "Depois de instalar o utilitário Windows®, clique duas vezes no arquivo torrent e ele será adicionado à tarefa Download Master automaticamente."
							 ],
							[
							 "Rozšíření USB",
							 "zpět",
							 "Použít Správce stahování",
							 "Instalovat nástroj Windows®",
							 "krok",
							 "Klepněte na název nebo ikonu Správce stahování na stránce aplikace USB.",
							 "Správce stahování se otevře v novém okně prohlížeče. Klepnutím na Add (Přidat) přidejte úlohu stahování.",
							 "Chcete-li stáhnout soubor BitTorrent nebo NZB, klepnutím na Choose file (Vybrat soubor) odešlete soubor *.torrent nebo *.nzb.",
							 "Chcete-li stahovat ze serveru FTP, HTTP nebo z odkazu Magnet, zkopírujte a vložte adresu URL do pole URL.",
							 "Pokud server FTP vyžaduje uživatelské jméno, heslo, v oblasti úloh je zobrazen vykřičník <img src=\"images/appinstall/warning_16X16.png\">.",
							 "Klepněte na vykřičník a zadejte uživatelské jméno a heslo.",
							 "Stáhněte a nainstalujte nástroj Windows®.",
							 "Stáhnout!",
							 "Po nainstalování nástroje Windows® poklepejte na soubor torrent, který bude automaticky přidán do úlohy Správce stahování."
							 ],
							[
							 "USB-udvidelse",
							 "tilbage",
							 "Brug Download Master",
							 "Installer Windows® værktøjet",
							 "trin",
							 "Klik på Download Master navnet, eller på ikonet på siden i USB-programmet.",
							 "Download Master vil åbne i et nyt vindue. Klik på Add (Tilføj), for at tilføje en download-opgave.",
							 "For at downloade en BitTorrent eller NZB-fil, skal du klikke på Choose file (Vælg fil), hvorefter *.torrent eller *.nzb-filen uploades.",
							 "For at downloade FTP, HTTP eller et Magnet link, skal du kopierer og sætte URL-adressen i URL-feltet.",
							 "Hvis FTP-siden anmoder om et brugernavn og en adgangskode, vil der være et udråbstegn <img src=\"images/appinstall/warning_16X16.png\"> i opgaveoprådet.",
							 "Klik venligst på udråbstegnet, for at indtaste dit brugernavn og adgangskode.",
							 "Download og installer Windows® værktøjet.",
							 "Download nu!",
							 "Når du har installeret Windows® værktøjet, skal du dobbeltklik på torrent-filen, hvorefter den automatisk føjes til Download Master-opgaven."
							 ],
							[
							 "USB-jatkokaapeli",
							 "takaisin",
							 "Käytä Download Masteria",
							 "Asenna Windows®-apuohjelma",
							 "vaihe",
							 "Napsauta Download Master -nimeä tai -kuvaketta USB-sovellussivulla.",
							 "Download Master avautuu uudessa selainikkunassa. Napsauta Add (Lisää)-painiketta lisätäksesi lataustehtävän.",
							 "Voit ladata BitTorrent- tai NZB-tiedoston napsauttamalla Choose file (Valitse tiedosto) ladataksesi *.torrent- tai *.nzb-tiedoston.",
							 "Voit ladata FTP-, HTTP- tai Magnet-linkistä kopioimalla URL-osoitteen ja liittämällä sen URL-kenttään.",
							 "Jos FTP-sivuston käyttöön tarvitaan käyttäjänimi ja salasana, tehtäväalueella näkyy huutomerkki <img src=\"images/appinstall/warning_16X16.png\">.",
							 "Napsauta huutomerkkiä näppäilläksesi käyttäjätunnuksen ja salasanan.",
							 "Lataa ja asenna Windows®-apuohjelma.",
							 "Lataa nyt!",
							 "Kaksoisnapsauta Windows®-apuohjelman asennuksen jälkeen torrent-tiedostoa, jolloin se lisätään automaattisesti Download Master -tehtäviin."
							 ],
							[
							 "Sambungan USB",
							 "kembali",
							 "Gunakan Download Master",
							 "Pasang utiliti Windows®",
							 "langkah",
							 "Klik pada nama Download Master atau ikon pada halaman aplikasi USB.",
							 "Download Master akan dibuka pada tetingkap penyemak imbas baru. Klik Add (Tambah) untuk menambah tugasan muat turun.",
							 "Untuk memuat turun fail BitTorrent atau NZB, klik Choose file (Pilih fail) untuk memuat naik fail *.torrent atau *.nzb.",
							 "Untuk memuat turun FTP, HTTP atau pautan Magent, salin dan tampal URL ke medan URL.",
							 "Jika tapak FTP memerlukan nama pengguna, kata laluan, terdapat tanda seru <img src=\"images/appinstall/warning_16X16.png\"> di dalam kawasan tugasan.",
							 "Sila klik pada tanda seru untuk memasukkan nama pengguna dan kata laluan.",
							 "Muat turun dan pasang utiliti Windows®.",
							 "Muat Turun Sekarang!",
							 "Selepas memasang utiliti Windows®, klik dua kali fail torrent dan ia akan ditambah secara automatik ke tugasan Download Master."
							 ],
							[
							 "USB-utvidelse",
							 "tilbake",
							 "Bruk Download Master",
							 "Last ned Windows®-verktøyet.",
							 "trinn",
							 "Klikk på Download Master-navnet eller -ikonet på USB-applikasjonssiden.",
							 "Download Master åpnes i et nytt nettleservindu. Klikk på Add (Legg til) for å legge til en nedlastingsoppgave.",
							 "Klikk på Choose File (Velg fil) for å laste opp *.torrent- eller *.nzb-filen for deretter å laste ned BitTorrent- eller NZB-filen.",
							 "For å laste ned en FTP-, HTTP- eller Magnet-link, kopierer og limer du URL-en inn i adressefeltet.",
							 "Hvis det kreves brukernavn og passord på FTP-siden, står det et utropstegn <img src=\"images/appinstall/warning_16X16.png\"> i oppgaveområdet.",
							 "Klikk på utropstegnet for å taste inn brukernavnet og passordet.",
							 "Last ned og installer Windows®-verktøyet.",
							 "Last ned nå!",
							 "Etter at du har installert Windows®-verktøyet, dobbeltklikker du på torrent-filen. Den legges da automatisk til Download Master-oppgavelisten."
							 ],
							[
							 "Przedłużacz USB",
							 "cofnij",
							 "Użyj programu Download Master",
							 "Zainstaluj narzędzie Windows®",
							 "czynność",
							 "Kliknij nazwę programu Download Master lub ikonę na stronie aplikacji USB.",
							 "Program Download Master zostanie otworzony w nowym oknie przeglądarki. Kliknij Add (Dodaj), aby dodać zadanie pobierania.",
							 "Aby pobrać plik BitTorrent lub NZB, kliknij Choose file (Wybierz plik) w celu przesłania pliku *.torrent lub *.nzb.",
							 "Aby pobrać przez FTP, HTTP albo łącze Magnet, skopiuj i wklej URL w polu URL.",
							 "Jeśli strona FTP wymaga nazwy użytkownika, hasła, w obszarze zadań pojawi się znak wykrzyknika <img src=\"images/appinstall/warning_16X16.png\">.",
							 "Kliknij znak wykrzyknika, aby wprowadzić nazwę użytkownika i hasło.",
							 "Pobierz i zainstaluj narzędzie Windows®.",
							 "Pobierz teraz!",
							 "Po instalacji narzędzia Windows®, kliknij dwukrotnie plik torrenta, po czym zostanie on dodany automatycznie do zadania programu Download Master."
							 ],
							[
							 "USB-utbyggnad",
							 "tillbaka",
							 "Använd Download master",
							 "Installera Windows® verktyg",
							 "steg",
							 "Klicka på Download Master namnet eller ikonen på USB-programsidan.",
							 "Download Master kommer att öppnas ett nytt bläddrarfönster. Klicka på Add (Lägg till) för att lägga till en nedladdningsuppgift.",
							 "För att ladda ned BitTorrent eller NZB filen, klicka på Choose file (Välj fil) för att ladda upp *.torrent eller *.nzb filen.",
							 "För att ladda ned FTP, HTTP eller Magnet länken, kopiera och klistra in URL i URL-fältet.",
							 "Om FTP webbplatsen behöver användarnamn, lösenord finns det ett utropstecken <img src=\"images/appinstall/warning_16X16.png\"> i aktivietetsfältet.",
							 "Klicka på utropstecknet för att knappa in användarnamnet och lösenordet.",
							 "Ladda ned och installera Windows® verktyget.",
							 "Ladda ned nu!",
							 "Efter att Windows® verktyget installerats, dubbelklicka på torrent-filen och den kommer automatiskt att läggas till i Download Master uppgiften för nedladdning"
							 ],
							[
							 "การขยาย USB",
							 "ย้อนกลับ",
							 "ใช้ดาวน์โหลดมาสเตอร์",
							 "ติดตั้งยูทิลิตี้ Windows",
							 "ขั้น",
							 "คลิกชื่อหรือไอคอน ดาวน์โหลดมาสเตอร์ ในหน้าแอปพลิเคชั่น USB",
							 "ดาวน์โหลดมาสเตอร์ จะเปิดในหน้าต่างเบราเซอร์ใหม่ คลิก Add (เพิ่ม) เพื่อเพิ่มงานดาวน์โหลด",
							 "ในการดาวน์โหลดไฟล์บิตทอร์เร้นต์ หรือ NZB, คลิก Choose file (เลือกไฟล์) เพื่ออัปโหลดไฟล์ *.torrent หรือ *.nzb",
							 "ในการดาวน์โหลด FTP, HTTP หรือ Magnet ลิงค์, ให้คัดลอกและวาง URL ไปยังฟิลด์ URL",
							 "ถ้า FTP ไซต์จำเป็นต้องใส่ชื่อผู้ใช้, รหัสผ่าน, จะมีเครื่องหมายตกใจ <img src=\"images/appinstall/warning_16X16.png\"> ในบริเวณงาน",
							 "โปรดคลิกเครื่องหมายตกใจ เพื่อป้อนชื่อผู้ใช้และรหัสผ่าน",
							 "ดาวน์โหลดและติดตั้งยูทิลิตี้ Windows®",
							 "ดาวน์โหลดเดี๋ยวนี้!",
							 "หลังจากการติดตั้งยูทิลิตี้ Windows®, ดับเบิลคลิกไฟล์ทอร์เร้นต์ และไฟล์จะถูกเพิ่มไปยังรายการงานดาวน์โหลดมาสเตอร์โดยอัตโนมัติ"
							 ],
							[
							 "USB Uzantısı",
							 "geri",
							 "Download Master'ı Kullanma",
							 "Windows® Programını Yükleyin",
							 "adım",
							 "USB uygulama sayfasından Download Master adına veya simgesine tıklayın.",
							 "Download Master yeni bir tarayıcı penceresinde açılacaktır. Bir indirme görevi eklemek için Add (Ekle) üzerine tıklayın.",
							 "BitTorrent veya NZB dosyasını indirmek için, Choose file (Dosya seç)’e tıklayarak *.torrent veya *.nzb dosyasını yükleyin.",
							 "FTP, HTTP veya Magnet link indirmek için, URL’yi URL alanın kopyalayın ve yapıştırın.",
							 "FTP sitesi kullanıcı adı, şifreye ihtiyaç duyarsa, görev alanında bir ünlem işareti <img src=\"images/appinstall/warning_16X16.png\"> bulunur.",
							 "Kullanıcı adını ve parolayı girmek için lütfen ünlem işaretine tıklayın.",
							 "Windows® yardımcı programını indirin ve yükleyin.",
							 "Şimdi İndir!",
							 "Windows® programını kurduktan sonra, torrent dosyasına iki kez tıklayınca kendiliğinden İndirme Yöneticisi (Download Master) görevine eklenecektir."
							 ],
							[
							 "USB拡張",
							 "戻る",
							 "Download Masterを使用する",
							 "Windows® ユーティリティのダウンロード",
							 "手順",
							 "USBアプリケーションの画面でDownload Masterの名前またはそのアイコンをクリックします。",
							 "Download Masterが新しいブラウザーウィンドウで開きます。「追加」をクリックし、ダウンロードタスクを追加します。",
							 "BitTorrent またはNZBファイルをダウンロードするには、「Choose file」を選択し、「*.torrent」または「*.nzb」ファイルをアップロードします。",
							 "FTP、HTTP、Magnet linkをダウンロードする場合は、URLをURLの欄にコピーします。",
							 "FTPサイトでユーザー名とパスワードの入力が必要な場合は、タスクエリアにエクスクラメーションマーク<img url=\"\">が表示されます。",
							 "エクスクラメーションマークをクリックし、ユーザー名とパスワードを入力してください。",
							 "Windows® ユーティリティをダウンロード・インストールします。",
							 "今すぐダウンロードしましょう！",
							 "Windows®ユーティリティをインストールした後、Torrentファイルをダブルクリックすると、Download Masterのタスクに自動的に追加されます。"
							 ],
							 [
							 "Estensione USB",
							 "indietro",
							 "Usa Master Download",
							 "Installa utility Windows®",
							 "step",
							 "Cliccate sul nome Download Master o sull'icona nella pagina dell'applicazione USB.",
							 "Il Download Master si aprirà in una nuova finestra del browser. Cliccate su Add per aggiungere un download.",
							 "Per scaricare tramite BitTorrent o NZB cliccate su Choose file per caricare il file *.torrent o il file *.nzb corrispondenti.",
							 "Per scaricare tramite FTP, HTTP o Magnet link copiate e incollate il collegamento del file nel campo URL.",
							 "Se per la connessione al sito FTP sono necessari nome utente e password apparirà un punto esclamativo <img src=\"images/appinstall/warning_16X16.png\"> nell'area dei processi in corso.",
							 "Cliccate sul punto esclamativo per inserire nome utente e password.",
							 "Scarica e installa l'utility Windows®.",
							 "Scarica adesso!",
							 "Dopo aver installato l'utility Windows® fate doppio click sul file .torrent e questo sarà aggiunto alla coda dei Download Master automaticamente."
							 ],
							 [
							 "USB-hosszabbító",
							 "Vissza",
							 "Download Master használata",
							 "Windows® segédprogram telepítése",
							 "Lépés",
							 "Kattintson a Download Master nevére vagy ikonjára az USB alkalmazási oldalon.",
							 "A Download Master új böngészőablakban nyílik meg. Letöltési feladat hozzáadásához kattintson a Hozzáadás gombra.",
							 "BitTorrent vagy NZB fájl letöltéséhez kattintson a Fájl választása lehetőségre, és töltse fel a *.torrent vagy *.nzb fájlt.",
							 "FTP, HTTP vagy Magnet hivatkozás letöltéshez másolja ki a vágólapra és illessze be az URL-címet az URL mezőbe.",
							 "Ha az FTP oldal felhasználónevet és jelszót kér, akkor a feladatterületen található <imgsrc=\"images/appinstall/warning_16X16.png\"> rész mellett egy felkiáltójel látható.",
							 "A felhasználónév és jelszó megadásához kattintson a felkiáltójelre.",
							 "Windows® segédprogram letöltése és telepítése.",
							 "Letöltés most!",
							 "A Windows® segédprogram telepítését követően kattintson kétszer a torrent fájlra, így azt a rendszer automatikusan hozzáadja a Download Master programhoz."
							 ],
							 [
							 "Prelungire USB",
							 "înapoi",
							 "Utilizare Download Master",
							 "Instalare utilitar Windows®",
							 "pas",
							 "Faceţi clic pe numele sau pictograma Download Master din pagina USB application (Aplicaţie USB).",
							 "Download Master se va deschide într-o nouă fereastră de browser. Faceţi clic pe Add (Adăugare) pentru a adăuga o sarcină de descărcare.",
							 "Pentru a descărca fişierul BitTorrent sau NZB, faceţi clic pe Choose file (Alegere fişier) pentru a încărca fişierul *.torrent sau *.nzb.",
							 "Pentru a descărca legătura FTP, HTTP sau Magnet, copiaţi şi lipiţi locaţia URL în câmpul URL.",
							 "Dacă site-ul FTP necesită un nume de utilizator şi o parolă, va exista un semn de exclamare <img src=\"images/appinstall/warning_16X16.png\"> în zona de sarcini.",
							 "Faceţi clic pe semnul de exclamare pentru a introduce numele de utilizator şi parola.",
							 "Descărcaţi şi instalaţi utilitarul Windows®.",
							 "Descărcare acum!",
							 "După ce aţi instalat utilitarul Windows®, faceţi dublu clic pe fişierul torent şi acesta va fi adăugat automat în lista de sarcini a Download Master."
							 ],
							 [
							 "Розширення USB",
							 "назад",
							 "Користуйтеся програмою завантаження",
							 "Інсталюйте застосунок Windows®",
							 "крок",
							 "Натисніть назву програми завантаження або піктограму на сторінці задачі USB",
							 "Програма завантаження відкриється в новому вікні браузера. Клацніть Add (Додати), щоб додати завдання завантаження.",
							 "Щоб завантажити файл BitTorrent або NZB, клацніть Choose file (Вибрати файл), щоб завантажити файл *.torrent або *.nzb.",
							 "Щоб завантажити посилання FTP, HTTP або Magnet, скопіюйте і вставте URL у поле URL",
							 "Якщо для сайта FTP потрібні ім'я користувача і пароль, у ділянці задачі <img src=\"images/appinstall/warning_16X16.png\"> стоятиме знак оклику",
							 "Будь ласка, клацніть по знаку оклику, щоб ввести ім'я користувача і пароль",
							 "Завантажте та інсталюйте застосунок Windows®",
							 "Завантажте зараз!",
							 "Інсталювавши застосунок Windows®, двічі клацніть по файлу потоку, і він буде автоматично доданий до завдань програми завантаження"
							 ],
							 [
							 "Extensión USB",
							 "atrás",
							 "Utilizar Download Master (Maestro de descarga)",
							 "Instalar la utilidad Windows®",
							 "paso",
							 "Haga clic en el nombre o el icono Download Master (Maestro de descarga) en la página de la aplicación USB.",
							 "Download Master (Maestro de descarga) se abrirá en una nueva ventana del explorador. Haga clic en Add (Agregar) para agregar una tarea de descarga.",
							 "Para descargar el archivo BitTorrent o NZB, haga clic en Choose file (Elegir archivo) para cargar el archivo *.torrent o *.nzb.",
							 "Para descargar el vínculo FTP, HTTP o Magnet, copie y pegue la dirección URL en el campo de dirección URL.",
							 "Si el sitio FTP necesita nombre de usuario y contraseña, aparecerá un símbolo de exclamación <img src=\"images/appinstall/warning_16X16.png\"> en el área de tareas.",
							 "Haga clic en el símbolo de exclamación para escribir el nombre de usuario y la contraseña.",
							 "Descargue e instale la utilidad Windows®.",
							 "¡Descargar ahora!",
							 "Después de instalar la utilidad Windows®, haga doble clic en el archivo Torrent y se agregará a la tarea Download Master (Maestro de descarga) automáticamente."
							 ]
							]
